<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use DateTime;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0;');
        DB::table('municipios')->truncate();
        DB::table('municipios')->insert(
            [
                ['nombre'=>'Boaco','IdDepartamento'=>'1', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Camoapa','IdDepartamento'=>'1', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San José de los Remates','IdDepartamento'=>'1', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Lorenzo','IdDepartamento'=>'1', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santa Lucia','IdDepartamento'=>'1', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Teustepe','IdDepartamento'=>'1', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Diriamba','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Dolores','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Rosario','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Jinotepe','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Conquista','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Paz de Oriente','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Marcos','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santa Teresa','IdDepartamento'=>'2', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Chichigalpa','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Chinandega','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Cinco Pinos','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Corinto','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Realejo','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Viejo','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Posoltega','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Puerto Morazán','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Francisco del Norte','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Pedro del Norte','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santo Tomás del Norte','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Somotillo','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Villanueva','IdDepartamento'=>'3', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Acoyapa','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Comalapa','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Cuapa','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Coral','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Juigalpa','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Libertad','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Pedro de Lóvago','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santo Domingo','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santo Tomás','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Villa Sandino','IdDepartamento'=>'4', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Bonanza','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Mulukukú','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Prinzapolka','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Puerto Cabezas','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Rosita','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Siuna','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Waslala','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Waspán','IdDepartamento'=>'5', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Bluefields','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Corn Island','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Desembocadura de Río Grande','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Ayote','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Rama','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Tortuguero','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Kukra Hill','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Cruz de Río Grande','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Laguna de Perlas','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Muelle de los Bueyes','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Nueva Guinea','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Paiwas','IdDepartamento'=>'6', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Condega','IdDepartamento'=>'7', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Estelí','IdDepartamento'=>'7', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Trinidad','IdDepartamento'=>'7', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Pueblo Nuevo','IdDepartamento'=>'7', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Juan de Limay','IdDepartamento'=>'7', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Nicolás','IdDepartamento'=>'7', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Diriá','IdDepartamento'=>'8', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Diriomo','IdDepartamento'=>'8', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Granada','IdDepartamento'=>'8', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Nandaime','IdDepartamento'=>'8', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Cuá','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Jinotega','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Concordia','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San José de Bocay','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Rafael del Norte','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Sebastián de Yalí','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santa María de Pantasma','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Wiwilí de Jinotega','IdDepartamento'=>'9', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Achuapa','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Jicaral','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Sauce','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Paz Centro','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Larreynaga','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'León','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Nagarote','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Quezalguaque','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santa Rosa del Peñón','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Telica','IdDepartamento'=>'10', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Las Sabanas','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Palacagüina','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San José de Cusmapa','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Juan de Río Coco','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Lucas','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Somoto','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Telpaneca','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Totogalpa','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Yalagüina','IdDepartamento'=>'11', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Ciudad Sandino','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Crucero','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Managua','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Mateare','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Francisco Libre','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Rafael del Sur','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Ticuantepe','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Tipitapa','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Villa El Carmen','IdDepartamento'=>'12', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Catarina','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'La Concepción','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Masatepe','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Masaya','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Nandasmo','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Nindirí','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Niquinohomo','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Juan de Oriente','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Tisma','IdDepartamento'=>'13', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Ciudad Darío','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Tuma - La Dalia','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Esquipulas','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Matagalpa','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Matiguás','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Muy Muy','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Rancho Grande','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Río Blanco','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Dionisio','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Isidro','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Ramón','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Sébaco','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Terrabona','IdDepartamento'=>'14', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Ciudad Antigua','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Dipilto','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Jícaro','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Jalapa','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Macuelizo','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Mozonte','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Murra','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Ocotal','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Quilalí','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Fernando','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Santa María','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Wiwilí','IdDepartamento'=>'15', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Almendro','IdDepartamento'=>'16', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'El Castillo','IdDepartamento'=>'16', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Morrito','IdDepartamento'=>'16', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Carlos','IdDepartamento'=>'16', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Juan del Norte','IdDepartamento'=>'16', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Miguelito','IdDepartamento'=>'16', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Altagracia','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Belén','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Buenos Aires','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Cárdenas','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Moyogalpa','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Potosí','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Rivas','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Jorge','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'San Juan del Sur','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime],
                ['nombre'=>'Tola','IdDepartamento'=>'17', 'created_at'=>new DateTime, 'updated_at'=>new DateTime]
                
              
            ]
        );
        DB::statement('SET FOREIGN_KEY_CHECKS = 1;');
    }
}
